curl -i -X POST "https://mercader-server.onrender.com/api/juegos/?idCategory=69ed016079b9149b96f0e91a" \
  -H "Authorization: Bearer mock_token" \
  -F "titulo=Test" \
  -F "descripcion=Test Desc" \
  -F "cant_min_pers=2" \
  -F "cant_max_pers=4" \
  -F "duracion_min=30" \
  -F "duracion_max=60" \
  -F "precio=100" \
  -F "disponible=true" \
  -F "activo=true" \
  -F "cantidad=5" \
  -F "services=compra" \
  -F "portada=@package.json"
